---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app: jackett
    kubernetes.io/name: "jackett"
spec:
  selector:
    app: jackett
  ports:
  - name: jackett
    nodePort: 30117
    port: 30117
    targetPort: 9117
  type: NodePort
