apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: mms
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31907
    port: 80
    protocol: TCP
    targetPort: 9117
  selector:
    app: jackett
  sessionAffinity: None
  type: LoadBalancer
