---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jackett
  namespace: mms
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9117
          protocol: TCP
        env:
        - name: PUID
          value: "10003"
        - name: PGID
          value: "10003"
        - name: TZ
          value: "Europe/Amsterdam"
        volumeMounts:
        - name: jackett-localtime
          mountPath: /etc/localtime
        - name: jackett-config
          mountPath: /config
      volumes:
      - name: jackett-localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: jackett-config
        hostPath:
          path: /mms/config/jackett
