apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: mms
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32402
    port: 80
    protocol: TCP
    targetPort: 8112
  selector:
    app: deluge
  sessionAffinity: None
  type: LoadBalancer
