---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  labels:
    app: deluge
    kubernetes.io/name: "deluge"
spec:
  selector:
    app: deluge
  ports:
  - name: deluge-web
    nodePort: 30112
    port: 30112
    targetPort: 8112
  - name: deluge-daemon
    nodePort: 30846
    port: 30846
    targetPort: 58846
  - name: deluge-p2p-tcp
    nodePort: 30328
    port: 30328
    targetPort: 64328
  - name: deluge-p2p-udp
    nodePort: 30328
    port: 30328
    targetPort: 64328
    protocol: UDP
  type: NodePort
