apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
  name: deluge
  namespace: mms
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deluge
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deluge
    spec:
      containers:
      - env:
        - name: PUID
          value: "10002"
        - name: PGID
          value: "10002"
        - name: TZ
          value: Europe/Amsterdam
        - name: UMASK_SET
          value: "022"
        image: linuxserver/deluge:latest
        imagePullPolicy: Always
        name: deluge
        ports:
        - containerPort: 8112
          protocol: TCP
        - containerPort: 58846
          protocol: TCP
        - containerPort: 64328
          protocol: TCP
        - containerPort: 64328
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: deluge-config
        - mountPath: /downloads
          name: deluge-downloads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mms/config/deluge
          type: ""
        name: deluge-config
      - hostPath:
          path: /mms/Downloads
          type: ""
        name: deluge-downloads
