apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: mms
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32400
    port: 80
    protocol: TCP
    targetPort: 32400
  selector:
    app: plex
  sessionAffinity: None
  type: LoadBalancer
