---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: plex
  namespace: mms
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      # hostNetwork: true
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:latest
        imagePullPolicy: Always
        # list of ports taken from off image docs https://hub.docker.com/r/plexinc/pms-docker/
        ports:
        - containerPort: 32400
          protocol: TCP
        - containerPort: 32400
          protocol: UDP
        - containerPort: 32469
          protocol: TCP
        - containerPort: 32469
          protocol: UDP
        - containerPort: 5353
          protocol: UDP
        - containerPort: 1900
          protocol: UDP
        - containerPort: 3005
          protocol: TCP
        - containerPort: 8324
          protocol: TCP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        env:
        - name: PLEX_UID
          value: "10002"
        - name: PLEX_GID
          value: "10001"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: ALLOWED_NETWORKS
          value: "172.16.0.0/16,10.0.0.0/22,10.112.0.0/28,10.113.0.0/24,10.111.0.0/24"
        - name: ADVERTISE_IP
          value: http://10.111.0.111:32400/
        volumeMounts:
        - name: plex-config
          mountPath: /config
        - name: plex-media
          mountPath: /data
      nodeSelector:
        disktype: ssd
      volumes:
        - name: plex-media
          hostPath:
            path: /mms
        - name: plex-config
          hostPath:
            path: /mms/config/plex
