apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: mms
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonarr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "10002"
        - name: PGID
          value: "10004"
        - name: TZ
          value: Europe/Amsterdam
        image: linuxserver/sonarr:latest
        imagePullPolicy: IfNotPresent
        name: sonarr
        ports:
        - containerPort: 8989
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: sonarr-localtime
        - mountPath: /config
          name: sonarr-config
        - mountPath: /downloads
          name: sonarr-downloads
        - mountPath: /tv
          name: sonarr-tv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: File
        name: sonarr-localtime
      - hostPath:
          path: /mms/config/sonarr
          type: ""
        name: sonarr-config
      - hostPath:
          path: /mms/Downloads
          type: ""
        name: sonarr-downloads
      - hostPath:
          path: /mms/TV
          type: ""
        name: sonarr-tv
