apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: mms
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30109
    port: 80
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
  sessionAffinity: None
  type: LoadBalancer
