apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: mms
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: radarr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "10002"
        - name: PGID
          value: "10005"
        - name: TZ
          value: Europe/Amsterdam
        image: linuxserver/radarr:latest
        imagePullPolicy: Always
        name: radarr
        ports:
        - containerPort: 7878
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: radarr-localtime
        - mountPath: /config
          name: radarr-config
        - mountPath: /downloads
          name: radarr-downloads
        - mountPath: /movies
          name: radarr-movies
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: File
        name: radarr-localtime
      - hostPath:
          path: /mms/config/radarr
          type: ""
        name: radarr-config
      - hostPath:
          path: /mms/Downloads
          type: ""
        name: radarr-downloads
      - hostPath:
          path: /mms/Movies
          type: ""
        name: radarr-movies
