apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: mms
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32195
    port: 80
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
  sessionAffinity: None
  type: LoadBalancer
