---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
    kubernetes.io/name: "radarr"
spec:
  selector:
    app: radarr
  ports:
  - name: radarr
    nodePort: 30878
    port: 30878
    targetPort: 7878
  type: NodePort
