---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  labels:
    app: unifi
    kubernetes.io/name: "unifi"
spec:
  selector:
    app: unifi
  ports:
  - port: 8080
    name: uap-inform
    targetPort: 8080
    nodePort: 30080
  - port: 8443
    name: controller-gui-api
    targetPort: 8443
    nodePort: 30443 
  - port: 8880
    name: http-redirect
    targetPort: 8880
  - port: 8843
    name: https-redirect
    targetPort: 8843
  - port: 6789
    name: throughput-measurement
    targetPort: 6789
  - port: 3478
    name: stun-port
    targetPort: 3478
    nodePort: 30478
    protocol: UDP
  - port: 8881
    name: wireless-client-redirector-port1
    targetPort: 8881
  - port: 8882
    name: wireless-client-redirector-port2
    targetPort: 8882
  - port: 10001
    name: ap-discovery
    targetPort: 10001
    protocol: UDP
  type: NodePort
