apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-nfs
  namespace: kube-system
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.112.0.11
    path: "/volume1/mms/config/unifi/config"
