apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: unifi-nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
