---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: unifi
  namespace: kube-system
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
        image: linuxserver/unifi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8443
        - containerPort: 8843
        - containerPort: 8880
        - containerPort: 6789
        - containerPort: 3478
          protocol: UDP
        - containerPort: 8881
        - containerPort: 8882
        - containerPort: 10001
          protocol: UDP
        env:
        - name: PUID
          value: "10006"
        - name: PGID
          value: "10006"
        volumeMounts:
        - name: unifi-config
          mountPath: /config
      volumes:
      - name: unifi-config
        hostPath:
          path: /mms/config/unifi/config
